### ISSUE TITLE
KeyError: 'XRef' when creating editable form

### ISSUE THREAD

**Issue by aseams** [jorisschellekens/borb-examples#10]
While trying to recreate a form we use in office (currently filled out by hand), I came across this XRef error. The form consists of a logo/title sharing the top of the page, followed by the inputs shown below. Unfortunately I cannot share the other elements (logo, title, subtitle) without redacting them to oblivion.
The script executes perfectly when commenting out this specific table.

**Edit:** Let me also mention that I'd prefer to match the original layout (with mostly two label/field combinations per line). Having nine rows was a compromise when I thought that might be the issue.

The offending FlexibleWidthColumn:
```
layout.add(
    FlexibleColumnWidthTable(number_of_columns=2, number_of_rows=9)
    .add(Paragraph("User Name: "))
    .add(TextField(field_name="username"))
    .add(Paragraph("ID: "))
    .add(TextField(field_name="eid"))
    .add(Paragraph("Computer Name: "))
    .add(TextField(field_name="newpcname"))
    .add(Paragraph("Replacing Computer: "))
    .add(TextField(field_name="oldpcname"))
    .add(Paragraph("S/N: "))
    .add(TextField(field_name="oldserial"))
    .add(Paragraph("Keep in Service"))
    .add(TextField(field_name="service"))
    .add(Paragraph("Location"))
    .add(TextField(field_name="location"))
    .add(Paragraph("Model: "))
    .add(TextField(field_name="model"))
    .add(Paragraph("S/N: "))
    .add(TextField(field_name="serial"))
    .set_padding_on_all_cells(Decimal(2), Decimal(2), Decimal(2), Decimal(2))
    .no_borders()
)
```

Stack trace:
```
Traceback (most recent call last):
  File "c:\Users\user\Documents\python\PDFGen\main.py", line 122, in <module>
    main()
  File "c:\Users\user\Documents\python\PDFGen\main.py", line 92, in main 
    layout.add(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\page_layout\multi_column_layout.py", line 194, in add
    layout_rect = layout_element.layout(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\layout_element.py", line 290, in layout     
    return self.calculate_layout_box_and_do_layout(page, bounding_box)    
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\layout_element.py", line 303, in calculate_layout_box_and_do_layout
    layout_box = self._calculate_layout_box(page, bounding_box)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\layout_element.py", line 213, in _calculate_layout_box
    returned_layout_box = self._calculate_layout_box_without_padding(     
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\layout_element.py", line 241, in _calculate_layout_box_without_padding
    layout_rect = self._do_layout_without_padding(page, bounding_box)     
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\table\flexible_column_width_table.py", line 
87, in _do_layout_without_padding    
    t.calculate_min_and_max_width()  
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\table\table.py", line 86, in calculate_min_and_max_width
    max_bounding_box: Rectangle = self._calculate_layout_box(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\layout_element.py", line 213, in _calculate_layout_box
    returned_layout_box = self._calculate_layout_box_without_padding(     
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\table\table.py", line 123, in _calculate_layout_box_without_padding
    return self._layout_element._calculate_layout_box(page, bounding_box) 
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\layout_element.py", line 213, in _calculate_layout_box
    returned_layout_box = self._calculate_layout_box_without_padding(     
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\layout_element.py", line 241, in _calculate_layout_box_without_padding
    layout_rect = self._do_layout_without_padding(page, bounding_box)     
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\forms\text_field.py", line 161, in _do_layout_without_padding
    self._init_widget_dictionary(page, layout_rect)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\borb\pdf\canvas\layout\forms\text_field.py", line 98, in _init_widget_dictionary
    catalog: Dictionary = page.get_root()["XRef"]["Trailer"]["Root"]  # type: ignore [attr-defined]
KeyError: 'XRef'
```

**Comment by jorisschellekens** [comment]
The problem:
1. `FlexibleColumnWidthTable` needs to know the `min` and `max` area each `LayoutElement` is going to take up.
2. `FormField` objects attempt to insert their non-visible configuration in the PDF `Document` as soon as they are laid out
3. Calculation of `min` and `max` triggers layout on an incomplete `Document` (which does not yet contain an `XRef`)

I'm going to check what can be done about it.

You can use `FixedColumnWidthTable` which should behave just fine.

**Comment by jorisschellekens** [comment]
Fixed. Shall be in next release `v2.0.22`.
