### ISSUE TITLE
Exception of openig certain files

### ISSUE THREAD

**Issue by sirCamp** [jorisschellekens/borb-examples#12]
Hi, I'm trying to open a set of PDFs.
On this set exists a sub-set that makes the library crash. 

I reported the stack trace of the exception.

```
Traceback (most recent call last):
  File "/home/scampese/Repository/AuraTests/borb_test.py", line 36, in <module>
    main()
  File "/home/scampese/Repository/AuraTests/borb_test.py", line 26, in main
    doc = PDF.loads(in_file_handle, [l1])
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/pdf/pdf.py", line 54, in loads
    return ReadAnyObjectTransformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/reference/xref_transformer.py", line 140, in transform
    trailer = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/object/dictionary_transformer.py", line 46, in transform
    v = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/reference/reference_transformer.py", line 103, in transform
    transformed_referenced_object = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/page/root_dictionary_transformer.py", line 84, in transform
    transformed_root_dictionary = t.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/object/dictionary_transformer.py", line 46, in transform
    v = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/reference/reference_transformer.py", line 103, in transform
    transformed_referenced_object = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/object/dictionary_transformer.py", line 46, in transform
    v = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/object/array_transformer.py", line 46, in transform
    object_to_transform[i] = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/reference/reference_transformer.py", line 103, in transform
    transformed_referenced_object = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/page/page_dictionary_transformer.py", line 62, in transform
    v = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/object/dictionary_transformer.py", line 46, in transform
    v = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/object/dictionary_transformer.py", line 46, in transform
    v = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/reference/reference_transformer.py", line 103, in transform
    transformed_referenced_object = self.get_root_transformer().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/any_object_transformer.py", line 100, in transform
    return super().transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/transformer.py", line 123, in transform
    out = h.transform(
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/read/object/stream_transformer.py", line 53, in transform
    object_to_transform = decode_stream(object_to_transform)
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/filter/stream_decode_util.py", line 74, in decode_stream
    transformed_bytes = RunLengthDecode.decode(transformed_bytes)
  File "/home/scampese/anaconda3/envs/python_3_8/lib/python3.8/site-packages/borb/io/filter/run_length_decode.py", line 34, in decode
    n = bytes_in[i + 1]
IndexError: index out of range

Process finished with exit code 1
```
**N.B.:** with other libraries like pdfquery or textextract I'm able to open the same file without problems

Do you have a suggestion on how to deal with it?

My env:
+ python 3.8.12

Thanks!

**Comment by jorisschellekens** [comment]
Hi,

This is the examples repository of `borb`.
Your error is not about any of the examples, but about the library itself.

Please log your bug on the right repository. 
Also, when you log a bug about reading (or being unable to read) a PDF, please enclose the PDF as an attachment.

Kind regards,
Joris Schellekens
