### ISSUE TITLE
"Font %s can not represent '%s'" %

### ISSUE THREAD

**Issue by mrfrankstein** [jorisschellekens/borb-examples#31]
There is any solution for this?

```
Exception has occurred: AssertionError
Font SDGWMI+OpenSans-Semibold can not represent ''
  File "C:\Users\pc\Desktop\archive.py", line 16, in main
    doc = SimpleFindReplace.sub("Jots", "Joris", doc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\Desktop\archive.py", line 23, in <module>
    main()
AssertionError: Font SDGWMI+OpenSans-Semibold can not represent ' '

```

```

Traceback (most recent call last):
  File "C:\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,      
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      
  File "C:\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\pc\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\pc\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\pc\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\pc\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\pc\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,      
  File "c:\Users\pc\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    page.apply_redact_annotations()
    page.apply_redact_annotations()
  File "C:\Python311\Lib\site-packages\borb\pdf\page\page.py", line 152, in apply_redact_annotations
    .read(io.BytesIO(self["Contents"]["DecodedBytes"]), [])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\borb\pdf\canvas\canvas_stream_processor.py", line 300, in read
    raise e
  File "C:\Python311\Lib\site-packages\borb\pdf\canvas\canvas_stream_processor.py", line 294, in read
    operator.invoke(self, operands, event_listeners)  File "C:\Python311\Lib\site-packages\borb\pdf\canvas\redacted_canvas_stream_processor.py", line 302, in invoke
    self._write_chunk_of_text(
  File "C:\Python311\Lib\site-packages\borb\pdf\canvas\redacted_canvas_stream_processor.py", line 230, in _write_chunk_of_text
    )._write_text_bytes()
      ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\borb\pdf\canvas\layout\text\chunk_of_text.py", line 200, in _write_text_bytes
    return self._write_text_bytes_in_hex()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\borb\pdf\canvas\layout\text\chunk_of_text.py", line 242, in _write_text_bytes_in_hex
    assert cid is not None, "Font %s can not represent '%s'" % (
           ^^^^^^^^^^^^^^^
AssertionError: Font SDGWMI+OpenSans-Semibold can not represent
```

The code is:
```

from borb.pdf import Document
from borb.pdf import PDF
from borb.toolkit import SimpleFindReplace
import typing

def main():
    doc: typing.Optional[Document] = None
    with open("archive.pdf", "rb") as pdf_file_handle:
        doc = PDF.loads(pdf_file_handle)

    assert doc is not None

    doc = SimpleFindReplace.sub("Jots", "Joris", doc)

    with open("output2.pdf", "wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, doc)

if __name__ == "__main__":
    main()


```

**Comment by jorisschellekens** [comment]
There's no aesthetically pleasing solution that would always work.

Not every font can represent every character. 
The trivial example for instance is "Helvetica can not represent characters in the Chinese script".

Your example might be a bit more nuanced.

You see, in order to save on space, a PDF document can contain so called "subset" fonts. It's essentially a font that is stripped down to only contain the characters needed to render the PDF.

So, if your PDF does not contain an uppercase X, the subset font would not contain an uppercase X.

You can recognize a subset font by its name. It typically starts with some random chars and a "+" sign, followed by the name of the font from which it was derived.

In order to really be aesthetically pleasing, `SimpleFindReplace` would have to find the closest matching font whenever it detects a situation in which a particular character can not be rendered in the font that was originally used.

That's currently out of scope.

Can you attach your PDF document though? Just so I can verify.

**Comment by pig123123** [comment]
It seems that I have met this kind of problem too.

`from borb.pdf import Document
from borb.pdf import PDF
from borb.toolkit import SimpleFindReplace

import typing


def main():

    #尝试读取PDF
    doc: typing.Optional[Document] = None
    with open("chapter_1.pdf", "rb") as pdf_file_handle:
        doc = PDF.loads(pdf_file_handle)

    assert doc is not None

    #替换
    doc = SimpleFindReplace.sub(pattern="Cambridge", repl="Math",doc= doc)

    #储存替换文本后的文件
    with open("output_001.pdf","wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, doc)

if __name__ == "__main__":
    main()

print("finish_borb")
`

And here is the error code
`Traceback (most recent call last):
  File "/Users/rzhu/Desktop/python_learning/pdf_watermark_remove/SimpleFindReplaceWithborb.py", line 25, in <module>
    main()
  File "/Users/rzhu/Desktop/python_learning/pdf_watermark_remove/SimpleFindReplaceWithborb.py", line 18, in main
    doc = SimpleFindReplace.sub(pattern="Cambridge", repl="Math",doc= doc)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/toolkit/text/simple_find_replace.py", line 77, in sub
    page.apply_redact_annotations()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/page/page.py", line 151, in apply_redact_annotations
    RedactedCanvasStreamProcessor(self, Canvas(), rectangles_to_redact)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/canvas_stream_processor.py", line 300, in read
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/canvas_stream_processor.py", line 294, in read
    operator.invoke(self, operands, event_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/redacted_canvas_stream_processor.py", line 192, in invoke
    self._write_chunk_of_text(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/redacted_canvas_stream_processor.py", line 118, in _write_chunk_of_text
    canvas_stream_processor._redacted_content += ChunkOfText(  # type: ignore [attr-defined]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/layout/text/chunk_of_text.py", line 200, in _write_text_bytes
    return self._write_text_bytes_in_hex()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/borb/pdf/canvas/layout/text/chunk_of_text.py", line 242, in _write_text_bytes_in_hex
    assert cid is not None, "Font %s can not represent '%s'" % (
AssertionError: Font CKLXOK+SourceSansPro-Regular can not represent '�'`


and this is a weird character, in my computer it is like this:
![截屏2023-05-27 下午9 42 41](https://github.com/jorisschellekens/borb-examples/assets/134779050/6efa13ad-3d6d-4a35-af1e-7f998c31a365)

then I extract text from that pdf:
![截屏2023-05-27 下午9 50 24](https://github.com/jorisschellekens/borb-examples/assets/134779050/3b4e3a98-dd21-4485-a8c5-c3f0770cfc7d)

but in the pdf ,there's nothing behind the word 'such as', 'identify' and 'theorem'. That means I can't see the weird character in the pdf.

Here is the pdf

[chapter_1.pdf](https://github.com/jorisschellekens/borb-examples/files/11582346/chapter_1.pdf)

I use Pycharm with Mac Big Sur.

**Comment by romanesko** [comment]
The same thing. Not a single Cyrillic character can be displayed. Do these included fonts support unicode at all?

**Comment by jorisschellekens** [comment]
Hi guys,

The standard 14 fonts, and the characters they can represent are determined by the PDF specification (you can find an early version of it in the repository). I try to create a product that adheres to the specification. I think that's what most customers would like.

As such, it is not my choice whether a given alphabet is included or not. The error you are getting is `borb` warning you that the selected font simply can not represent the character you're trying to insert. The solution is always the same: **use a different font**.

Kind regards,
Joris Schellekens

**Comment by romanesko** [comment]
The only monotype font on this collection doesn't support Unicode. Most customers would like to have the Unicode support despite the specification. Or at least to have the ability co add a custom TTF font

**Comment by jorisschellekens** [comment]
You can set the `Font` of a `Paragraph` using a custom `Font`, made from a `.ttf` file.
You can find this in the example repository [here](https://github.com/jorisschellekens/borb-examples#241-setting-the-font-of-a-paragraph).

This is also a test:
https://github.com/jorisschellekens/borb/blob/master/tests/pdf/canvas/font/test_add_paragraphs_using_truetype_fonts.py

This is `Pacifico-Regular` for instance:
https://github.com/jorisschellekens/borb/blob/master/tests/pdf/canvas/font/artifacts_test_add_paragraphs_using_truetype_fonts/output_003.pdf

I hope that assures you that it is in fact possible to use your own custom font.

Kind regards,
Joris Schellekens
