### ISSUE TITLE
Code Provided for Example 5.7's pdf is not working with borb 2.1.17

### ISSUE THREAD

**Issue by DrPlanecraft** [jorisschellekens/borb-examples#37]
I am currently following through tutorials and I have discovered that the example 5.7s example to extract all colors on a given pdf file is not working on my machine.

Below is the full Traceback output for my attempts to run the code
```
reading page
Traceback (most recent call last):
  File "c:\Users\Lenovo\OneDrive\Documents\LI ZHUOXI\ITE- College West\Lessons\Industrial Attachment Program\IAP Higher Nitec AI Applications\HumanKind Design Pte Ltd\Image and color Extraction.py", line 80, in <module>
    t.add(
  File "C:\Users\Lenovo\anaconda3\envs\HumanKind\Lib\site-packages\borb\pdf\canvas\layout\table\table.py", line 394, in add
    first_incomplete_row: int = min(
                                ^^^^
ValueError: min() arg is an empty sequence
```

The code I am running:
```py
#!chapter_005/src/snippet_013.py
from borb.io.read.types import Name, String, Dictionary
from borb.pdf import SingleColumnLayout
from borb.pdf import PageLayout
from borb.pdf import Paragraph
from borb.pdf import Document
from borb.pdf import Page
from borb.pdf import PDF
from borb.pdf import HexColor
from borb.pdf import Image
from borb.pdf import HexColor, RGBColor, Color
from borb.pdf.canvas.geometry.rectangle import Rectangle
from borb.pdf import ConnectedShape
from borb.pdf import Alignment
from borb.pdf import FlexibleColumnWidthTable
from borb.pdf import LineArtFactory
from borb.toolkit import ColorExtraction
import typing

from decimal import Decimal

# # create Document
# doc: Document = Document()

# # create Page
# page: Page = Page()

# # add Page to Document
# doc.add_page(page)

# # set a PageLayout
# layout: PageLayout = SingleColumnLayout(page)

# # the following code adds 3 paragraphs, each in a different color
# layout.add(Paragraph("Hello World!", font_color=HexColor("FF0000")))
# layout.add(Paragraph("Hello World!", font_color=HexColor("00FF00")))
# layout.add(Paragraph("Hello World!", font_color=HexColor("0000FF")))

# # the following code adds 1 image
# layout.add(
#     Image(
#         "https://images.unsplash.com/photo-1589606663923-283bbd309229?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8",
#         width=Decimal(256),
#         height=Decimal(256),
#     )
# )

# # store
# with open("ImageOutput.pdf", "wb") as out_file_handle:
#     PDF.dumps(out_file_handle, doc)

##############################################################################################

doc: typing.Optional[Document] = None
l: ColorExtraction = ColorExtraction()
with open("ImageOutput.pdf", "rb") as pdf_file_handle:
    doc = PDF.loads(pdf_file_handle, [l])
l.get_
# extract colors
colors: typing.Dict[Color, Decimal] = l.get_color()[0]

# create output Document
doc_out: Document = Document()

# add Page
p: Page = Page()
doc_out.add_page(p)

# add PageLayout
l: PageLayout = SingleColumnLayout(p)

# add Paragraph
l.add(Paragraph("These are the colors used in the input PDF:"))

# add Table
t: FlexibleColumnWidthTable = FlexibleColumnWidthTable(
    number_of_rows=3, number_of_columns=3, horizontal_alignment=Alignment.CENTERED
)
for c in colors.keys():
    t.add(
        ConnectedShape(
            LineArtFactory.droplet(
                Rectangle(Decimal(0), Decimal(0), Decimal(32), Decimal(32))
            ),
            stroke_color=c,
            fill_color=c,
        )
    )
t.set_padding_on_all_cells(Decimal(5), Decimal(5), Decimal(5), Decimal(5))
t.no_borders()
l.add(t)

# store
with open("outputImage_Colors.pdf", "wb") as pdf_file_handle:
    PDF.dumps(pdf_file_handle, doc_out)
```

**Comment by DrPlanecraft** [comment]
Update: Ignore the ```l.get_``` I was trying to find the method documentation linked to the get_color on my vscode editor

**Comment by jorisschellekens** [comment]
The stack trace seems to indicate that your problem comes from `Table` rather than `ColorExtraction`.

This could simply be because you are adding too much data to the `Table`.

Your `Table` has 3 rows and 3 columns. Are you sure you're only adding 9 `ConnectedShape` objects?

Kind regards,
Joris Schellekens

**Comment by DrPlanecraft** [comment]
Uh, Your example only had 9 colors, but following your example I got 3 more extra colors, namely an extra shade of red, green and purple, Currently seeking more professional help from my company designers

**Comment by DrPlanecraft** [comment]
Uh, Your example only had 9 colors, but following your example I got 3 more extra colors, namely an extra shade of purple, teal and light blue.
